[package]
name = "lisla"
version = "0.1.0"
authors = ["shohei909 <909mmsphere@gmail.com>"]

[lib]
name="lisla_lang"

[dependencies]
lisla_derive = { version = "0.1.0", path = "../lisla_derive" }

[dev-dependencies]
serde="1.0.11"
serde_json="1.0.2"