using litll.idl.std.tools.idl.TypeReferenceTools;
using litll.idl.std.tools.idl.EnumTools;
using litll.idl.std.tools.idl.TupleTools;
using litll.idl.std.tools.idl.TupleElementTools;
using litll.idl.std.tools.idl.StructTools;
using litll.idl.std.tools.idl.StructElementTools;
using litll.idl.std.tools.idl.FollowedTypeDefinitionTools;
using litll.idl.std.tools.idl.ArgumentTools;
using litll.idl.std.tools.idl.EnumConstructorTools;